# Generated by Django 4.2.1 on 2024-05-28 00:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_de_la_factua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado_de_la_factua', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_de_factura', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Numero_de_factura', models.IntegerField()),
                ('fecha_de_emicion', models.DateField()),
                ('cliente', models.CharField(max_length=50)),
                ('Items_de_factura', models.TextField()),
                ('Total', models.IntegerField()),
                ('Estado_de_la_factua', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.estado_de_la_factua')),
            ],
        ),
    ]
