# Generated by Django 4.2.1 on 2024-05-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('numero_de_factura', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('termino_en_dias', models.IntegerField()),
                ('fecha_de_vencimiento', models.DateField()),
                ('esta_pagodo', models.CharField(max_length=50)),
                ('estado', models.TextField()),
            ],
        ),
    ]
