# Generated by Django 4.2.1 on 2024-06-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_boleta', models.CharField(max_length=100)),
                ('Fecha_emision', models.DateField()),
                ('Cliente', models.CharField(max_length=100)),
                ('Items_boleta', models.TextField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Estado', models.CharField(max_length=50)),
            ],
        ),
    ]
