# Generated by Django 5.0.6 on 2024-07-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='Numero_de_factura',
            field=models.IntegerField(default=0),
        ),
    ]
