# Generated by Django 5.0.6 on 2024-07-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_facturas_numero_de_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='Numero_de_factura',
            field=models.IntegerField(),
        ),
    ]
